apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.otelCollector.name }}-config
  namespace: {{ .Values.namespace }}
data:
  otel-collector-config.yaml: |
    receivers:
{{- toYaml .Values.otelCollector.config.receivers | nindent 6 }}

    processors:
{{- toYaml .Values.otelCollector.config.processors | nindent 6 }}

    exporters:
{{- toYaml .Values.otelCollector.config.exporters | nindent 6 }}

    service:
{{- toYaml .Values.otelCollector.config.service | nindent 6 }}
