{{- if .Values.demos.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  connection: "host={{ .Values.postgres.name }}-svc.{{ .Values.namespace }}.svc.cluster.local port={{ .Values.postgres.service.port }} user={{ .Values.postgres.user }} password={{ .Values.postgres.password }} dbname={{ .Values.postgres.database }} sslmode=disable"
{{- end }}
